# Generated by Django 4.1.3 on 2022-11-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Myorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.CharField(max_length=10, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('productname', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('totalamount', models.IntegerField()),
                ('orderid', models.CharField(default='1', max_length=150)),
                ('orderdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('orderstatus', models.CharField(default='Placed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneno', models.CharField(max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
