# Generated by Django 4.1.3 on 2022-11-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanagement', '0001_initial'),
        ('gameadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.stock'),
        ),
        migrations.AddField(
            model_name='myorders',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameadmin.user'),
        ),
    ]
