# Generated by Django 4.1.3 on 2022-11-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='userid',
        ),
    ]
