# Generated by Django 4.1.3 on 2022-11-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0004_remove_myorders_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=150)),
                ('paymentmethod', models.CharField(max_length=100)),
                ('totalamount', models.IntegerField()),
                ('status', models.CharField(default='True', max_length=100, null=True)),
                ('orderid', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housename', models.CharField(default=None, max_length=100)),
                ('city1', models.CharField(default=None, max_length=100)),
                ('district1', models.CharField(default=None, max_length=100)),
                ('zipcode1', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
