# Generated by Django 4.1.3 on 2022-11-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0005_payment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myorders',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myorders',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='myorders',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gameadmin.address'),
            preserve_default=False,
        ),
    ]
