# Generated by Django 4.1.3 on 2022-12-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0012_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
