# Generated by Django 4.1.3 on 2022-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0013_alter_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
