# Generated by Django 4.1.3 on 2022-11-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=600)),
                ('image1', models.ImageField(upload_to='pics/')),
                ('image2', models.ImageField(upload_to='pics/')),
                ('image3', models.ImageField(upload_to='pics/')),
                ('image4', models.ImageField(upload_to='pics/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameadmin.categories')),
            ],
        ),
    ]
