# Generated by Django 4.1.3 on 2022-12-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
        ('cartmanagement', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userreference', models.CharField(max_length=200, null=True)),
                ('productname', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.stock')),
            ],
        ),
    ]
